spring:
  application:
    name: hello-zuul
  
server:
  port: 8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-admin
    api-b:
      path: /api/b/**
      serviceId: hello-admin
